### ISSUE TITLE
TSDB: wrong toTimestamp when calling range('key', 0, -1)

### ISSUE THREAD

**Issue by gmax0** [RedisTimeSeries/redistimeseries-py#108]
redistimeseries-py version: 1.4.3
redis-py version: 3.5.3

I'm instantiating a redistimeseries client via
```rts = Client(redis.Redis(host="XXX", port=6379, password="XXX")))```
and subsequently calling a few TS commands.

This command, however, fails.
```rts.range('key', 0, -1)```
The following stacktrace is thrown:
```  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: TSDB: wrong toTimestamp
```

Not sure if this can be addressed in this library as it seems like it's an issue with redis-py?
The equivalent range command executed directly in redis-cli performs as intended.

**Comment by AvitalFineRedis** [comment]
Hi @gmax0 
The equivalent range command (`TS.RANGE key 0 -1`) throws the same error.
If you wish to express the maximum possible timestamp, you can use `rts.range('key', '-', '+')`

**Comment by gmax0** [comment]
> Hi @gmax0
> The equivalent range command (`TS.RANGE key 0 -1`) throws the same error.
> If you wish to express the maximum possible timestamp, you can use `rts.range('key', '-', '+')`

Perfect, thank you!
