### ISSUE TITLE
Typo is usage examples: 'aggregationType' should be 'aggregation_type'

### ISSUE THREAD

**Issue by vjcalling** [RedisTimeSeries/redistimeseries-py#20]
Team,

I was trying out redistimeseries-py by following the documentation. In the usage examples, it's given as 'aggregationType' but when I use the same it throws an error. 

I went through the client.py code and found that it should be 'aggregation_type' not 'aggregationType'.

Can someone pls cross-check this and confirm?

**Comment by ashtul** [comment]
@vjcalling thank you!
