### ISSUE TITLE
Add does not update the key and value for a same timestamp

### ISSUE THREAD

**Issue by harishkumarr95** [RedisTimeSeries/redistimeseries-py#31]
For my requirement, I was using Redistimeseries module and I have been getting this error saying that 
> TSDB: Timestamp cannot be older than the latest timestamp in the time series

I want to update the Values in the key for the same timestamp by using the command 

> TS.ADD

I hope this is an issue as the value should be updated for the same timestamp and not throw an error.

**Comment by ashtul** [comment]
This behavior is not of the client but the RedisTimeSeries module.
We are not allowing to update a point thought we may support multiple values in one timestamp in the future.

**Comment by harishkumarr95** [comment]
Alright, Thank you @ashtul, expecting the feature to be up soon.

**Comment by ashtul** [comment]
@harishkumarr95 , please close this issue and open on the main repository
