### ISSUE TITLE
key error  'memoryUsage'

### ISSUE THREAD

**Issue by yutiansut** [RedisTimeSeries/redistimeseries-py#33]
In [6]: rts.info(3)
{'lastTimestamp': 0, 'retentionTime': 0, 'chunkCount': 1, 'maxSamplesPerChunk': 360, 'labels': [[b'Redis', b'Labs']], 'sourceKey': None, 'rules': []}
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-0ac279b287f9> in <module>()
----> 1 rts.info(3)

E:\redistimeseries-py\redistimeseries\client.py in info(self, key)
    263     def info(self, key):
    264         """Gets information of ``key``"""
--> 265         return self.execute_command(self.INFO_CMD, key)
    266
    267     def queryindex(self, filters):

C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py in execute_command(self, *args, **options)
    837         try:
    838             conn.send_command(*args)
--> 839             return self.parse_response(conn, command_name, **options)
    840         except (ConnectionError, TimeoutError) as e:
    841             conn.disconnect()

C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py in parse_response(self, connection, command_name, **options)
    857             raise
    858         if command_name in self.response_callbacks:
--> 859             return self.response_callbacks[command_name](response, **options)
    860         return response
    861

E:\redistimeseries-py\redistimeseries\client.py in __init__(self, args)
     23         self.sourceKey = response['sourceKey']
     24         self.chunkCount = response['chunkCount']
---> 25         self.memory_usage = response['memoryUsage']
     26         self.total_samples = response['totalSamples']
     27         self.labels = list_to_dict(response['labels'])

KeyError: 'memoryUsage'

**Comment by yutiansut** [comment]
environmemt: docker / redistimeseries

**Comment by yutiansut** [comment]
here is the raw response

```
{'lastTimestamp': 0, 'retentionTime': 0, 'chunkCount': 1, 'maxSamplesPerChunk': 360, 'labels': [[b'Redis', b'Labs']], 'sourceKey': None, 'rules': []}
```

**Comment by yutiansut** [comment]
docker log
```
λ  [master ≡ +0 ~1 -0 !]docker run -p 6379:6379 -it --rm redislabs/redistimeseries
Unable to find image 'redislabs/redistimeseries:latest' locally
latest: Pulling from redislabs/redistimeseries
f5d23c7fed46: Pull complete
5d1536028276: Pull complete
84e504b50c70: Pull complete
5e92c5cf44cf: Pull complete
60295726bf09: Pull complete
c0260bd3d479: Pull complete
6cbc7f8323c2: Pull complete
Digest: sha256:474a1cf44d11ea3ebc266551357e54a82569a6554b9b76c880de1bb8f062282e
Status: Downloaded newer image for redislabs/redistimeseries:latest
1:C 25 Dec 2019 17:16:30.027 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Dec 2019 17:16:30.028 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Dec 2019 17:16:30.028 # Configuration loaded
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.5 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 25 Dec 2019 17:16:30.028 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 25 Dec 2019 17:16:30.028 # Server initialized
1:M 25 Dec 2019 17:16:30.029 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 25 Dec 2019 17:16:30.029 * Module 'timeseries' loaded from /usr/lib/redis/modules/redistimeseries.so
1:M 25 Dec 2019 17:16:30.029 * Ready to accept connections

```

**Comment by ashtul** [comment]
@yutiansut 
We have recently updated both server and client. 
Are you using the latest versions?

**Comment by yutiansut** [comment]
> @yutiansut 
> We have recently updated both server and client. 
> Are you using the latest versions?

docker maybe the latest ， client for py  i install in the first time，so it should be the latest also，i installed from github and pip install -e .

**Comment by ashtul** [comment]
@yutiansut should be the docker. Can you try to run against edge?

**Comment by yutiansut** [comment]
@ashtul my docker 
```
λ  [master ≡ +0 ~1 -0 !]docker run -p 6379:6379 -it --rm redislabs/redistimeseries
Unable to find image 'redislabs/redistimeseries:latest' locally
latest: Pulling from redislabs/redistimeseries
f5d23c7fed46: Pull complete
5d1536028276: Pull complete
84e504b50c70: Pull complete
5e92c5cf44cf: Pull complete
60295726bf09: Pull complete
c0260bd3d479: Pull complete
6cbc7f8323c2: Pull complete
Digest: sha256:474a1cf44d11ea3ebc266551357e54a82569a6554b9b76c880de1bb8f062282e
Status: Downloaded newer image for redislabs/redistimeseries:latest
```

**Comment by Bobfrat** [comment]
@yutiansut @ashtul Seems to work using the edge tag, thanks

```
docker run -p 6379:6379 -d --rm redislabs/redistimeseries:edge
```

**Comment by ashtul** [comment]
Supported only from v1.2
