### ISSUE TITLE
Add support to TS.REVRANGE and TS.MREVRANGE 

### ISSUE THREAD

**Issue by ashtul** [RedisTimeSeries/redistimeseries-py#39]
@danni-m @K-Jo @gkorland @filipecosta90 
Shell we add a new command or add a reverse flag to TS.RANGE and TS.MRANGE which by default will be False?

**Comment by ashtul** [comment]
Ref RedisTimeSeries/RedisTimeSeries#292

**Comment by filipecosta90** [comment]
> Shell we add a new command or add a reverse flag to TS.RANGE and TS.MRANGE which by default will be False?

@ashtul the `TS.RANGE` behaviour remained the same. The only default behavior was in `TS.MRANGE`. IMHO I think we should keep the experience of other clients and the TSDB. With that in mind i think that we should add an extra argument to `mrange` function with the default value to false:

```
def mrange(self, from_time, to_time, filters,
                     aggregation_type=None, bucket_size_msec=0, with_labels=False):
```

what do you think?

**Comment by filipecosta90** [comment]
> @danni-m @K-Jo @gkorland @filipecosta90
> Shell we add a new command or add a reverse flag to TS.RANGE and TS.MRANGE which by default will be False?

IMHO I think we should add a new function considering this refers to a new command on the TSDB.

**Comment by K-Jo** [comment]
@filipecosta90 let's move this discussion to to the project: https://github.com/RedisTimeSeries/RedisTimeSeries/pull/292 or https://github.com/RedisTimeSeries/RedisTimeSeries/issues/254
I agree it should be two commands
