### ISSUE TITLE
v0.1.0 not working through pip install

### ISSUE THREAD

**Issue by matmichsyx** [RedisTimeSeries/redistimeseries-py#4]
Installing v0.1.0 via `pip install redistimeseries` does not include the actual library.
This is due to a missing __init__.py file under the redistimeseries package folder.
During pip install it can clearly be seen that no actual code of client.py is added:

`pip install . -vvv | grep 'adding'`
>   creating '/tmp/pip-wheel-y2ib8b0x/redistimeseries-0.1-cp36-none-any.whl' and adding '.' to it
>   adding 'redistimeseries-0.1.dist-info/top_level.txt'
>   adding 'redistimeseries-0.1.dist-info/WHEEL'
>   adding 'redistimeseries-0.1.dist-info/METADATA'
>   adding 'redistimeseries-0.1.dist-info/RECORD'`

**Comment by maguec** [comment]
We will be pushing an update to pip soon.  In the meanwhile, you can pip install from git to get the fixes that have been merged

requirements.txt
```
hiredis>=0.2.0
redis>=2.10
rmtest>=0.2
six>=1.10.0
git+https://github.com/RedisTimeSeries/redistimeseries-py
```

then:

```
pip install -r requirements.txt 
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import redistimeseries
>>> 
```

**Comment by ashtul** [comment]
Release v0.2.0 is now available.
