### ISSUE TITLE
Old version module in client.py

### ISSUE THREAD

**Issue by AlKorochkin** [RedisTimeSeries/redistimeseries-py#45]
Lines 66-70 in client .py contain:
```
MODULE_INFO = {
    'name': 'RedisTimeSeries',
     'ver': '0.2.0'
     }
```
Is this the correct information? 
Since the current version is 0.7.0.

**Comment by AlKorochkin** [comment]
Sorry, I compared the sources inside redistimeseries-py-0.7.0.tar.gz with the current state of the master branch, assuming they should be the same.
This was my mistake, as it was necessary to compare with the release commit.

The following block of code in clien.py (lines 66-70) misled me:
```
MODULE_INFO = {
    'name': 'RedisTimeSeries',
     'ver': '0.2.0'
     }
```

**Comment by gkorland** [comment]
Thanks for the comment, it seems like an old dead code.
Fixed: https://github.com/RedisTimeSeries/redistimeseries-py/pull/46
