### ISSUE TITLE
Update pip install version to capture latest changes to incrby

### ISSUE THREAD

**Issue by statmatt** [RedisTimeSeries/redistimeseries-py#51]
source code looks to have changed to accommodate the PR bringing `timestamp` parameter on the incrby command, but current `pip install` version is not capturing that change.

**Comment by ashtul** [comment]
Hi @statmatt 
Thank you for letting us know
A new version will be released soon

**Comment by gkorland** [comment]
@statmatt a new release was published https://pypi.org/project/redistimeseries/0.8.0/
