### ISSUE TITLE
Getting error 'redis.exceptions.ResponseError: TSDB: Timestamp cannot be older than the latest timestamp in the time series'

### ISSUE THREAD

**Issue by shubhamivane** [RedisTimeSeries/redistimeseries-py#55]
When I am executing add command inside a loop I getting an error here is the traceback with code.
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    rts.add('demo','*',1000)
  File "/Users/ave/Desktop/platform-charter/lib/python3.7/site-packages/redistimeseries/client.py", line 186, in add
    return self.execute_command(self.ADD_CMD, *params)
  File "/Users/ave/Desktop/platform-charter/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/ave/Desktop/platform-charter/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/ave/Desktop/platform-charter/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: TSDB: Timestamp cannot be older than the latest timestamp in the time series

And here is the code 
 from redistimeseries.client import Client
 rts = Client()
 rts.create('demo')
 while rts.info('demo').chunkCount == 1:
         rts.add('demo','*',1000)
Any kind of help is appreciated.
Thanks in advance

**Comment by gkorland** [comment]
The current version of RedisTimeSeries doesn't allow out of order insert.
Meaning if two calls are done in the same ms the second will be rejected.
The following PR https://github.com/RedisTimeSeries/RedisTimeSeries/pull/437 should extend this support, should be merged today.

**Comment by filipecosta90** [comment]
hi there @shubhamivane, as of RedisTimeSeries v1.4 you can now back-fill time series and also control duplicate samples ingestion. This issue is related to duplicate samples, with the following possible policies to handle it (docs link https://oss.redislabs.com/redistimeseries/configuration/#duplicate_policy):

>    BLOCK - an error will occur for any out of order sample
>    FIRST - ignore the new value
>    LAST - override with latest value
>    MIN - only override if the value is lower than the existing value
>    MAX - only override if the value is higher than the existing value
>    SUM - If a previous sample exists, add the new sample to it so that the updated value is equal to (previous + new). If no previous sample exists, set the updated value equal to the new value.

I've altered you example by specifying the 'SUM' duplicate policy, meaning that two samples that end up in the same timestamp will be added up.

```
from redistimeseries.client import Client
rts = Client()
rts.create('demo')

print("Inserting samples with an duplicate policy='sum'")

while rts.info('demo').chunkCount == 1:
    rts.add('demo','*',1000,duplicate_policy="sum")

print( "Total distinct timestamps: {}".format(rts.info("demo").total_samples))
```

If you run it, you should now see the following (or a similar) output:
```
$ python3 rts_55.py 
Inserting samples with an duplicate policy='sum'
Total distinct timestamps: 3773
```

Closing this issue given we now support/control duplicate policies.
Please feel free to reopen if you are not able to replicate the above.

**Comment by shubhamivane** [comment]
Thanks @filipecosta90 it worked
