### ISSUE TITLE
Bug in renaming TS key

### ISSUE THREAD

**Issue by cloud-rocket** [RedisTimeSeries/redistimeseries-py#84]
I run into the following situation (while using Python library)

Calling the following (via Python commands):

```
TS.CREATE sensor2 LABELS sensor_id 2
TS.ADD sensor2 1548149180000 26
RENAME sensor2 sendor22
TS.MRANGE - + WIDTHLABELS FILTER sensor_id=2
```

The result of MRANGE is returned with the old key (`sensor2`) instead of the new one (`sensor22`)

**Comment by gkorland** [comment]
Which version RedisTimeSeries are you using? I think we had such bug in an older server version.

**Comment by cloud-rocket** [comment]
I am using `redislabs/redistimeseries:edge` Docker image updated 6 days ago. I also tried image version 1.4.8 before.

**Comment by gkorland** [comment]
@cloud-rocket sorry you are right RedisTimeSeries doesn't support rename, when do you need to rename a key?

**Comment by cloud-rocket** [comment]
Mostly data-science related work - if we want to use Redis as a backend for manual data manipulations.

**Comment by gkorland** [comment]
@cloud-rocket a fix was push to the main branch of  RedisTimeSeries/RedisTimeSeries
