### ISSUE TITLE
Pubsub integration

### ISSUE THREAD

**Issue by cloud-rocket** [RedisTimeSeries/redistimeseries-py#85]
What should be the best way to approach even-driven integration with Redis TS.

I.e. 

* I would like one process to push data to multiple different time series streams (i.e. temperature / pressure with timestamps)
* All time-series streams are timestamped together (temperature and pressure are receiving the same timestamp every time)
* Other processes should do something when new values are available (i.e. to display it, process it and etc.).

Should this mechanism be addressed separately from TS data processing or is there any better way?

Thanks

**Comment by gkorland** [comment]
ref https://github.com/RedisTimeSeries/RedisTimeSeries/pull/680

**Comment by cloud-rocket** [comment]
Thanks @gkorland,

Do you think there is a chance it will be merged anytime soon?

**Comment by gkorland** [comment]
Yes, the plan is to either push it in the upcoming 1.6 or right after it

**Comment by gkorland** [comment]
ref RedisTimeSeries/RedisTimeSeries#680
RedisTimeSeries/RedisTimeSeries#675
